app.measurement.list:
    path: /measurement
    controller: App\Infrastructure\Controller\MeasurementController::list
app.login.logout:
    path: /logout
    controller: App\Infrastructure\Controller\LoginController::index
app.login.index:
    path: /
    controller: App\Infrastructure\Controller\LoginController::index
