app.login.index:
    path: /
    controller: App\Infrastructure\Controller\LoginController::index
    methods: get

app.login.login:
    path: /login
    controller: App\Infrastructure\Controller\LoginController::login
    methods: post
