app.api.measurement.list:
    path: /api/measurement
    controller: App\Infrastructure\Controller\Api\MeasurementController::list
    methods: get
app.api.sensor.register:
    path: /api/sensor
    controller: App\Infrastructure\Controller\Api\RegisterSensorController::register
    methods: put
app.api.sensor_type.list:
    path: /api/sensor-type
    controller: App\Infrastructure\Controller\Api\SensorTypeController::list
    methods: get
app.register.index:
    path: /register
    controller: App\Infrastructure\Controller\RegisterController::index
    methods: get
app.register.register:
    path: /register
    controller: App\Infrastructure\Controller\RegisterController::register
    methods: post
app.measurement.list.view:
    path: /measurement
    controller: App\Infrastructure\Controller\MeasurementController::listView
app.login.logout:
    path: /logout
    controller: App\Infrastructure\Controller\LoginController::index
app.login.index:
    path: /
    controller: App\Infrastructure\Controller\LoginController::index
